application: goo-reader
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: django
  version: "1.2"

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /ui/
  static_dir: static/ui

- url: /.*
  script: main.py
  login: required
